// Generated by Wrangler on Sat Oct 26 2024 18:13:40 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	STATUS_KV: KVNamespace;
	SLACK_VERIFICATION_TOKEN: string;
	SLACK_CHANNEL_ID: string;
	ENV: string;
}
