// Generated by Wrangler on Sat Sep 07 2024 13:25:16 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	STATUS_KV: KVNamespace;
	SLACK_VERIFICATION_TOKEN: string;
	SLACK_CHANNEL_ID: string;
	FEIDE_CLIENT_ID: string;
	FEIDE_CLIENT_SECRET: string;
	FEIDE_REDIRECT_URI: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	GITHUB_REDIRECT_URI: string;
	RESEND_API_TOKEN: string;
	ENV: string;
	APP_URL: string;
	R2: R2Bucket;
	DB: D1Database;
}
