#:schema node_modules/wrangler/config-schema.json
name = "programmerbar-api"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = [ "nodejs_compat" ]
workers_dev = false

[[routes]]
pattern = "api.programmer.bar"
custom_domain = true


[[kv_namespaces]]
binding = "STATUS_KV"
id = "ef92306a34d24af19a14d9c0cd3fc5ab"


[[r2_buckets]]
binding = "R2"
bucket_name = "profile-pictures"


[[d1_databases]]
database_id = "026a2ca4-3fdd-48ac-895f-fbe234e9a6a4"
database_name = "progbar-db"
binding = "DB"
migrations_dir = "migrations"
migrations_table = "__drizzle_migrations"
